# Generated by Django 5.1.1 on 2025-02-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_app_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
