# Generated by Django 5.1.1 on 2025-02-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subcategory_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
