# Generated by Django 5.1.1 on 2025-02-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_sub_categoies_app_sub_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='user_screenshot',
            field=models.URLField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
